### ISSUE TITLE
Please pin the version of the `nf-validation` plugin!

### ISSUE THREAD

**Issue by mirpedrol** [nf-core/crisprseq#117]
### Description of feature

Hello!

⚠️ The `nf-validation` plugin will have soon a new release (v2.0) which has breaking changes. 
This will break the usage of all pipelines that don't pin the version of this plugin, as Nextflow tries to pull the latest version.

- ❓  How to pin the version:
Add this to your `nextflow.config` file (notice the **`@1.1.3`**):
```
plugins {
    nf-validation@1.1.3
}
```

- 🚨  Release a patch release as soon as possible!
Either if you already pinned the version on your dev branch or if you are going to add it now, please release this changes ASAP, to avoid breaking the usage of the latest version of your pipeline when the new version of `nf-validation` comes out.

- 🤓  How to use the new version of nf-validation?
If you want to be prepared for the new version of nf-validation, this will use the latest version of a JSON Schema draft. You will have to update the `nextflow_schema.json` and `input_schema.json` files (and any other JSON schemas that you use!).
You can find a migration guide [here](https://nextflow-io.github.io/nf-validation/latest/migration_guide/).

**Comment by LaurenceKuhl** [comment]
Closing this as it's done :)
