### ISSUE TITLE
Copy original file rather than softlink

### ISSUE THREAD

**Issue by zhouzhendiao** [nf-core/crisprseq#120]
### Description of feature

Softlinks became invalid after `nextflow clean`. It's not convenient sometimes, especially when I want to backup results. Could this pipeline copy results from cache rather than just softlink?

**Comment by LaurenceKuhl** [comment]
Hi @zhouzhendiao this should be fixed in the next release! In the meantime you can try running it with the dev branch. Just to be sure, could you please paste the command you use to execute the pipeline?
Thank you, 
Laurence

**Comment by zhouzhendiao** [comment]
> Hi @zhouzhendiao this should be fixed in the next release! In the meantime you can try running it with the dev branch. Just to be sure, could you please paste the command you use to execute the pipeline? Thank you, Laurence

Hi @LaurenceKuhl ,
Here is command: 
```
nohup nextflow run /local_path/nf-core-crisprseq-2.0.0/workflow \
    --analysis screening \
    --genome GRCh38 \
    --library library_file \
    --mle_design_matrix treatment_vs_control.txt \
    -profile singularity \
    --igenomes_base  local_path  \
    -offline \
    --outdir . \
    --input samplesheet.csv \
    -config user.config \
    -resume \
    --max_cpus 16 \
    --max_memory 64.GB \
    --max_time 256.h &

# clean
nextflow log | awk -F '\t' '{print $3}' | tail -4 | xargs -i nextflow clean {} -f
/bin/rm -r .nextflow* null/ work/ pipeline_info/
```

**Comment by LaurenceKuhl** [comment]
Hi we are currently planning the next release and i will get back to you to make sure everything works!

**Comment by zhouzhendiao** [comment]
Thanks!

**Comment by LaurenceKuhl** [comment]
Hi @zhouzhendiao, could you please check the documentation and try again with version 2.2.0 and let me know if it works?
