### ISSUE TITLE
Improve documentation describing day0 label

### ISSUE THREAD

**Issue by jeremymsimon** [nf-core/crisprseq#165]
### Description of feature

I've read the `crisprseq` and `MAGeCK` documentation a few times and the description and function of the `day0_label` is still a bit unclear to me, both in terms of how it should be specified (especially if there are multiple control samples/replicates) and what specifically it does. 

Let's say I have 3 control samples, and 3 treated samples, should the `day0_label` be set to `control` as is specified in my contrasts? Or should it be a comma-separated list of e.g. `Control_Rep1,Control_Rep2,Control_Rep3`? Or is it only appropriate for a true time-course experiment?

Further, according to the [MAGeCK documentation](https://sourceforge.net/p/mageck/wiki/Home/) the day0 label is a required parameter, but it does not seem to be required for `crisprseq` to run--I get MAGeCK counts and MLE results regardless. Is it figuring out a label automatically based on the contrasts, or is this a bug?

Thanks!

**Comment by LaurenceKuhl** [comment]
Hi @jeremymsimon this is normally now more thoroughly described, if you still find it confusing feel free to re open this issue :)
