### ISSUE TITLE
No such variable CUTADAPT (v.2.2.0)

### ISSUE THREAD

**Issue by joannakraw** [nf-core/crisprseq#180]
### Problem description:

I encountered an error while running the pipeline with the cutadapt option, specifically when passing adapter sequences using the `five_prime_adapter `and `three_prime_adapter `parameters. The pipeline execution fails with the following error message:

```
ERROR ~ No such variable: CUTADAPT

 -- Check script '/pod-data/pipelines/new_crisprseq/with_error/crisprseq/./workflows/crisprseq_screening.nf' at line: 89 or see '.nextflow.log' file for more details
```

### Workaround:

I have resolved this issue locally by making the following changes:

* Replaced `CUTADAPT.out` with `CUTADAPT_FIVE_PRIME` in line 89.
* Replaced `CUTADAPT.out` with `CUTADAPT_THREE_PRIME `in line 98.
These modifications allowed the pipeline to run without encountering the No such variable error. I attach the whole fragment of the modified code below:

#### Modified code
In the `workflows/crisprseq_screening.nf`:
```
        //set adapter seq to null to make it compatible with crispr targeted
        ch_cutadapt = ch_input.combine(Channel.value([[]]))
        if(params.five_prime_adapter) {
            CUTADAPT_FIVE_PRIME(
                ch_cutadapt
            )
            CUTADAPT_FIVE_PRIME.out.reads.combine(Channel.value([[]])).set { ch_cutadapt }
            ch_cutadapt.map{ meta, fastq, proto  ->
                meta.id = "${meta.id}_trim"
                [meta, fastq, proto]
            }.set { ch_cutadapt }

            ch_multiqc_files = ch_multiqc_files.mix(CUTADAPT_FIVE_PRIME.out.log.collect{it[1]})
            ch_versions = ch_versions.mix(CUTADAPT_FIVE_PRIME.out.versions)
        }

        if(params.three_prime_adapter) {
            CUTADAPT_THREE_PRIME(
                ch_cutadapt
            )
            ch_cutadapt = CUTADAPT_THREE_PRIME.out.reads.combine(Channel.value([[]]))
            ch_multiqc_files = ch_multiqc_files.mix(CUTADAPT_THREE_PRIME.out.log.collect{it[1]})
            ch_versions = ch_versions.mix(CUTADAPT_THREE_PRIME.out.versions)
        }
````

### Command used and terminal output

```console
nextflow run main.nf -profile k8s,docker -params-file parameters.json

ERROR ~ No such variable: CUTADAPT

 -- Check script '/pod-data/pipelines/new_crisprseq/with_error/crisprseq/./workflows/crisprseq_screening.nf' at line: 89 or see '.nextflow.log' file for more details
```

#### Nextflow info: 

- Version: 23.10.0 build 5889
- Created: 15-10-2023 15:07 UTC
- System: Linux 6.1.0-12-amd64
- Runtime: Groovy 3.0.19 on OpenJDK 64-Bit Server VM 17.0.8+7-LTS
- Encoding: UTF-8 (UTF-8)

**Comment by LaurenceKuhl** [comment]
Hi @joannakraw 
thank you so much!! Would you actually mind opening a PR with your contribution? If you're unsure how to go about it i would be happy to help!
Laurence

**Comment by LaurenceKuhl** [comment]
Hi Joanna,

Thanks!! don't hesitate to just open it and tag me if you have any questions :)

**Comment by LaurenceKuhl** [comment]
Hi @joannakraw, could you let me know why you re opened this? thanks!

**Comment by joannakraw** [comment]
Hi @LaurenceKuhl, I've clicked close by mistake, so I've reopened it again. I didn't know if I'm supposed to close this issue or you, sorry for confusion!
