### ISSUE TITLE
Pipeline breaking when I tried to run with -r 2.1.1  instead of -r dev

### ISSUE THREAD

**Issue by AASTHAPAL9** [nf-core/crisprseq#183]
### Description of the bug

Hi, 

I am not sure if this any compatibility issue but I couldn't run the pipeline with -r 2.1.1 which was suggested by one of the nfcore crisprseq developer. However when I did get something using -r dev it failed at some other step. I haven't been able to traceback the error and would appreciate any help in debugging. 

### Command used and terminal output

```console
nextflow run nf-core/crisprseq -r 2.1.1 --input samplesheet_w_control.csv --mle_design_matrix design_matrix.txt --library final_input_sgrna.tsv --analysis screening --outdir /home/ap764/mageck/output -profile conda
```

### Relevant files

![Screenshot 2024-07-23 at 11 57 49 PM](https://github.com/user-attachments/assets/674d66d8-0192-46a9-9c33-b06c3d1d5ea0)

The error when I ran the same command with -r dev : 

`executor >  local (8)
[90/f186a3] NFCORE_CRISPRSEQ:CRISPRSEQ_SCREENING:FASTQC (POST-KCNM-CDR-O)      | 5 of 5 ✔
[ad/da22ac] NFC…R-O,PRE-CDR-O,POST-EGF-CDR-O,POST-KCNM-CDR-O,POST-PTPRZ-CDR-O) | 1 of 1 ✔
[7b/c72af1] NFC…RISPRSEQ:CRISPRSEQ_SCREENING:MAGECK_MLE_MATRIX (design_matrix) | 1 of 1 ✔
[8d/013eae] NFC…_CRISPRSEQ:CRISPRSEQ_SCREENING:MAGECK_FLUTEMLE (design_matrix) | 1 of 1, failed: 1 ✘
[-        ] NFCORE_CRISPRSEQ:CRISPRSEQ_SCREENING:MULTIQC                       -
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/crisprseq] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_CRISPRSEQ:CRISPRSEQ_SCREENING:MAGECK_FLUTEMLE (design_matrix)'

Caused by:
  Process `NFCORE_CRISPRSEQ:CRISPRSEQ_SCREENING:MAGECK_FLUTEMLE (design_matrix)` terminated with an error exit status (127)

Command executed [/home/ap764/.nextflow/assets/nf-core/crisprseq/templates/template_fluteMLE.R]:

  #!/usr/bin/env Rscript
  #### author: Laurence Kuhlburger
  #### Released under the MIT license. See git repository (https://github.com/nf-core/crisprseq) for full license text.
  ####
  #### graphs mageck MLE
  
  library(MAGeCKFlute)
  library(clusterProfiler)
  library(ggplot2)
  
  library(pathview)
  options(ggrepel.max.overlaps = Inf)
  mle <- read.table("design_matrix.gene_summary.txt", header = TRUE, sep = "	", stringsAsFactors = FALSE)
  
  if("design_matrix" == "day0") {
      beta_strings <- grep("\\.beta", colnames(mle), value = TRUE)
      before_beta <- sub("\\.beta.*", "", beta_strings)
      unique_strings <- unique(before_beta)
      for(i in unique_strings) {
          tryCatch(
              {
                  FluteMLE(mle, treatname= i, proj=i, pathview.top=5)
              },
          error=function(e) {
                  print(paste("Could not run FluteMLE with project",i))
              }
          )
      }
  } else {
      beta_strings <- grep("\\.beta", colnames(mle), value = TRUE)
      before_beta <- sub("\\.beta.*", "", beta_strings)
      unique_strings <- unique(before_beta)
      for(i in unique_strings) {
          tryCatch(
              {
              FluteMLE(mle, treatname= i, proj=i,  , pathview.top=5)
              },
          error=function(e) {
                  print(paste("Could not run FluteMLE with project",i))
              }
          )
      }
  }
  
  version_file_path <- "versions.yml"
  version_flute <- paste(unlist(packageVersion("MAGeCKFlute")), collapse = ".")
  version_ggplot <- paste(unlist(packageVersion("ggplot2")), collapse = ".")
  version_clusterprofiler <- paste(unlist(packageVersion("clusterProfiler")), collapse = ".")
  version_pathview <- paste(unlist(packageVersion("pathview")), collapse = ".")
  
  f <- file(version_file_path, "w")
  writeLines('"NFCORE_CRISPRSEQ:CRISPRSEQ_SCREENING:MAGECK_FLUTEMLE":', f)
  writeLines("    MAGeCKFlute: ", f, sep = "")
  writeLines(version_flute, f)
  writeLines("    ggplot2: ", f, sep = "")
  writeLines(version_ggplot, f)
  writeLines("    clusterProfiler: ", f, sep = "")
  writeLines(version_clusterprofiler, f)
  writeLines("    pathview: ", f, sep = "")
  writeLines(version_pathview, f)
  close(f)

Command exit status:
  127

Command output:
  (empty)

Command error:
  /usr/bin/env: 'Rscript': No such file or directory

Work dir:
  /home/ap764/mageck/work/8d/013eae9d1032316baef01978a208a4

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
ERROR ~ Pipeline failed. Please refer to troubleshooting docs: https://nf-co.re/docs/usage/troubleshooting

 -- Check '.nextflow.log' file for details`

**Comment by LaurenceKuhl** [comment]
Hi this is now solved in the latest reelease :)
