### ISSUE TITLE
Is there a way to specify a common reference genome and run the analysis without protospacer 

### ISSUE THREAD

**Issue by npatel-ah** [nf-core/crisprseq#43]
### Description of feature

Hello, 

This is a great pipeline, I have a feature request, which I believe is simple, I have multiple samples, with the same reference genome, now providing reference genome within the sampleshseet.csv creates a separate reference.fasta for each of them with the sample name as contig_id.  Now when Minimap2 maps the Fastq to the references, all my bam files have different contigs, making it bit difficult to compare. 

Also, I see the a large portion of the pipeline can be run without "protospacer" , would it be possible to make it optional ? 

Best,

**Comment by mirpedrol** [comment]
I have added a new parameter `--reference` to allow an input fasta file to provide the same reference for all samples, if this parameter is given, then the reference field in the sample sheet is not required.
The protospacer is required as we use it to orient the reference and also for the parsing of SNPs and indels produced by the cut, but I also added a new parameter `--protospacer` which will work in the same way as `--reference`.

**Comment by npatel-ah** [comment]
Thank you so much for accommodating the change.

**Comment by benemead** [comment]
Hi there, appreciate these changes as this is my exact use case, but I've found that I'm getting errors when I specify both options in v2.1.1.

I have tried multiple combinations of specifying `protospacer` and `reference` in samplesheet and params (running via nextflow tower on aws batch) - the only way that leads to successful pipeline completion is with both specified only in the samplesheet.

When I use only `--protospacer` I encounter an error on `CRISPRSEQ_PLOTTER` where the protospacer is passed as `[]`.

When I use `--reference` as a path to a `.fasta` I encounter an error on `ORIENT_REFERENCE`:

```
Caused by:
  No such variable: id -- Check script '.nextflow/assets/nf-core/crisprseq/./workflows/../modules/local/orient_reference.nf' at line: 2
```

Appreciate any help you may have!

**Comment by mirpedrol** [comment]
Hi @benemead, thanks for reporting this! I will open a new issue to not lose track and have a look at the bug.
