### ISSUE TITLE
The number of labels (['KO14', 'KO-control']) must be equal to the number of fastq files provided.

### ISSUE THREAD

**Issue by zhouzhendiao** [nf-core/crisprseq#62]
### Description of the bug

command:
```
nextflow run /path-to/nf-core-crisprseq-2.0.0/workflow \
    -preview \
    --analysis screening \
    --library library.csv \
    --genome GRCh37 \
    -profile singularity \
    --igenomes_base /path-to/references \
    -offline \
    --outdir . \
    --input samplesheet.csv \
    -resume \
    --max_cpus 16 \
    --max_memory 64.GB \
    --max_time 256.h
```

samplesheet.csv
```
sample,fastq_1,fastq_2,condition
KO14,KO14_S1_L003_R1_001.fastq.gz,KO14_S1_L003_R2_001.fastq.gz,KO14
KO-control,KO-control_S6_L005_R1_001.fastq.gz,KO-control_S6_L005_R2_001.fastq.gz,KO-control
```

Error:
```
Command error:
  WARNING: Skipping mount /var/lib/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  INFO  @ Mon, 31 Jul 2023 18:09:46: Parameters: /usr/local/bin/mageck count -l library.csv -n count_table --sample-label KO14,KO-control --fastq KO14_S1_L003_R1_001.fastq.gz KO14_S1_L003_R2_001.fastq.gz KO-control_S6_L005_R1_001.fastq.gz KO-control_S6_L005_R2_001.fastq.gz
  INFO  @ Mon, 31 Jul 2023 18:09:46: Welcome to MAGeCK v0.5.9. Command: count
  ERROR @ Mon, 31 Jul 2023 18:09:46: The number of labels (['KO14', 'KO-control']) must be equal to the number of fastq files provided.
```

In `megeck count --fastq`, replicates seperated by comma, and samples with different condition seperated by space. However, crisprseq pipeline wrongly seperated fastq1 and fastq2 by comma, which fastq2  should be passed to  `--fastq-2`.

<img width="1263" alt="image" src="https://github.com/nf-core/crisprseq/assets/12294679/9dc2b16e-3eef-4818-97c0-b5a693f55a17">

```
  --fastq-2 FASTQ_2 [FASTQ_2 ...]
                        Paired sample fastq files (or fastq.gz files), the
                        order of which should be consistent with that in fastq
                        option.
```

**Comment by LaurenceKuhl** [comment]
Hi @zhouzhendiao,

thanks for adding the bug, working on the solution right now :) 
Thanks a lot for taking the time to open these issues, it really is helpful!
Laurence

**Comment by zhouzhendiao** [comment]
Hi @LaurenceKuhl ，

Thanks for your contribution!

**Comment by zhouzhendiao** [comment]
Hi @LaurenceKuhl ,

I left fastq2 empty and run everything successfully. Is it not necessary using fastq2 since sgRNA usually way shorter than read1? I tried add fastq2, however mageck failed to estimated trim length of 5' adatpter of read2.

**Comment by LaurenceKuhl** [comment]
Hi @zhouzhendiao 
could you please try rerunning this now with our new version 2.1.0?
Let me know if everything works smoothly :)

**Comment by LaurenceKuhl** [comment]
Hi, I will close this feel free to reopen if you have any updates
