### ISSUE TITLE
example file for `--rra_contrasts`

### ISSUE THREAD

**Issue by zhouzhendiao** [nf-core/crisprseq#71]
> MAGeCK RRA performs robust ranking aggregation to identify genes that are consistently ranked highly across multiple replicate screens. To run MAGeCK rra, `--rra_contrasts` should be used with a `csv` separated file stating the two conditions to be compared.

Hi, Can you show a example file for parameter `--rra_contrasts` if I start with fastq files. Sorry that I could not figure out the input for long time.

**Comment by mirpedrol** [comment]
Hi @zhouzhendiao, 
You can find the documentation for this parameter [here](https://nf-co.re/crisprseq/2.1.0/docs/usage/screening#mageck-rra), and an example [here](https://raw.githubusercontent.com/nf-core/test-datasets/crisprseq/testdata/rra_contrasts.txt). I hope this helps :)

**Comment by zhouzhendiao** [comment]
Thanks!
