### ISSUE TITLE
Targeted pipeline does not work with BWA

### ISSUE THREAD

**Issue by npatel-ah** [nf-core/crisprseq#73]
### Description of the bug

Hello, 

I was trying to the V2.0.0 using Docker with --aligner bwa, however, I am getting error. 

`nextflow run nf-core/crisprseq -profile docker  --overrepresented --input samplesheet.csv --analysis targeted --outdir $PWD  --aligner bwa  -r 2.0.0 -resume`

### Command used and terminal output

```console
nextflow run nf-core/crisprseq -profile docker  --overrepresented --input samplesheet.csv --analysis targeted --outdir $PWD -aligner bwa  -r 2.0.0 -resume


ERROR ~ Error executing process > 'NFCORE_CRISPRSEQ:CRISPRSEQ_TARGETED:BWA_INDEX (7)'

Caused by:
  Not a valid path value type: org.codehaus.groovy.runtime.NullObject (null)


Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

**Comment by mirpedrol** [comment]
Hello @npatel-ah, 
this is fixed now in the dev version. If you would like to test it previous to the next release, you can use `-r dev` with your command. But please note that this version will change while we continue developing.
Thanks for reporting the bug!
